title: Mathiodt
favicon: /assets/favicon.ico
description: Math,Operating System,Compiler,CG
global_tags: Operating System,Compiler and CG html5
copyright: © Golasowski 2021

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"